# Create a Report on Junctions

- name: Add a junction
  hosts: boulder-primary
  no_log: False
  connection: local
  roles:
    - role: start_config
    - role: add_junction_servers
      force: True

